name: daily.dev Bookmarks
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    # Runs every night
    - cron: '0 0 * * *'
    
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"