name: daily.dev Bookmarks
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    # Runs every night
    - cron: '0 0 * * *'

jobs:
  daily-dev-bookmarks:
    name: Update README with latest bookmarks from daily.dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.daily bookmarks
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "DEVDAILY"
          feed_list: "https://api.daily.dev/rss/b/3b8ddcae-5226-4f6d-a783-590fcdbe9353"
