name: Metrics
on:
    # Schedule daily updates
    schedule: [{ cron: '0 0 * * *' }]
    # (optional) Run workflow manually
    workflow_dispatch:
    # (optional) Run workflow when pushing on master/main
    push: { branches: ['main'] }
jobs:
    github-metrics:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
          - uses: jamcmich/metrics@main
            with:
              token: ${{ secrets.METRICS_SECRET }}
          
              # Achievements
              filename: metrics.plugin.achievements.svg
              base: ''
              plugin_achievements: yes
              plugin_achievements_secrets: yes
              plugin_achievements_display: detailed
              plugin_achievements_limit: 5


